# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yvmeng.wang
date_format: "ordinal"
title: "Yvmeng Wang's Website"
subtitle: "暂时啥都没有"
description: "我的个人博客"
keywords: Sam Wang, Yumeng Wang
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Yvmeng Wang
organization: yvmeng.wang
organization_url: http://yvmeng.wang
github_username: soqt
location: China
email: wym7230@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: soqt/soqt.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: soqt
    repo: blog-comments
    oauth:
        client_id: 5b14a25f600de08b7049
        client_secret: 67efc9ff551db36b2dbef2c2c3048bc96f6113dd
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: soqt
    repo: blog-comments
    clientID: 5b14a25f600de08b7049
    clientSecret: 67efc9ff551db36b2dbef2c2c3048bc96f6113dd
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
